FROM islandora/activemq:main-amd64

WORKDIR /opt/activemq

COPY Shanghai /usr/share/zoneinfo/Asia/Shanghai

RUN rm -f /etc/localtime && \
ln -s /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

EXPOSE 61616
EXPOSE 5672
EXPOSE 61613
EXPOSE 1883
EXPOSE 61614
EXPOSE 8161